name: Deploy Development to S3

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build webpack bundle
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy HTML files to S3 with no-cache
        run: |
          aws s3 sync . s3://tnjdynamicsite-dev --delete --exclude "*" --include "*.html" --cache-control="no-cache,no-store,must-revalidate" --content-type="text/html"

      - name: Deploy JavaScript files to S3 with no-cache
        run: |
          aws s3 sync . s3://tnjdynamicsite-dev --exclude "*" --include "*.js" --cache-control="no-cache,no-store,must-revalidate" --content-type="application/javascript"

      - name: Deploy remaining files to S3
        run: |
          aws s3 sync . s3://tnjdynamicsite-dev --delete --exclude ".git*" --exclude ".github*" --exclude "*.html" --exclude "*.js"
